apiVersion: apps/v1
kind: Deployment
metadata: { name: otel-collector }
spec:
  replicas: 1
  selector: { matchLabels: { app: otel-collector } }
  template:
    metadata: { labels: { app: otel-collector } }
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config=/conf/config.yaml"]
          ports: [{ containerPort: 4317 }, { containerPort: 4318 }]
          volumeMounts: [{ name: config, mountPath: /conf }]
      volumes:
        - name: config
          configMap: { name: otel-collector-config }
