apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: app-secrets
  data:
    - secretKey: example_api_key
      remoteRef:
        key: /three-tier/dev/app
        property: example_api_key
