apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sathish161084/observability_project.git
    targetRevision: main
    path: gitops/manifests/namespaces

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
