apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sathish161084/observability_project.git
    targetRevision: main
    path: helm/frontend

    helm:
      valueFiles:
        - ../../gitops/values/common-values.yaml
        - ../../gitops/values/frontend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated: { prune: true, selfHeal: true }
