apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker, observability: enabled }
      annotations:
        argocd-image-updater.argoproj.io/image-list: worker={{ .Values.image.repository }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 9102 }]
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.global.otelEndpoint | quote }}
            - name: OTEL_SERVICE_NAME
              value: "worker"
            - name: DEPLOYMENT_ENV
              value: {{ .Values.global.deploymentEnv | quote }}
            - name: KAFKA_BOOTSTRAP
              value: {{ .Values.global.kafkaBootstrap | quote }}
            - name: ORDER_TOPIC
              value: {{ .Values.global.orderTopic | quote }}
            - name: DLQ_TOPIC
              value: {{ .Values.global.dlqTopic | quote }}
            - name: KAFKA_SECURITY_PROTOCOL
              value: "SSL"
            - name: KAFKA_RETRY_ATTEMPTS
              value: "20"
            - name: KAFKA_RETRY_DELAY_SECONDS
              value: "15"
          resources:
{{ toYaml .Values.resources | indent 12 }}
