apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.11.0
    helm:
      values: |
        config:
          registries:
            - name: ECR
              prefix: 442999092835.dkr.ecr.us-east-1.amazonaws.com
              api_url: https://442999092835.dkr.ecr.us-east-1.amazonaws.com
              credentials: ext:/scripts/login.sh
        authScripts:
          enabled: true
          scripts:
            login.sh: |
              aws ecr get-authorization-token --region us-east-1 --output text --query 'authorizationData[].authorizationToken' | base64 -d
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
