apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.8.2
    helm:
      values: |
        grafana:
          enabled: true
          adminPassword: admin

        prometheus:
          enabled: true
          prometheusSpec:
            replicas: 1
            serviceMonitorSelectorNilUsesHelmValues: false

        alertmanager:
          enabled: true

        kubeStateMetrics:
          enabled: true

        nodeExporter:
          enabled: true

        defaultRules:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true