apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/three-tier-eks-platform-prod.git
    targetRevision: HEAD
    path: gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
